steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', './backend']

  # Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', './frontend']

  # Push the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend']

  # Push the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend']

  # Deploy backend service
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'backend-service', '--image', 'gcr.io/$PROJECT_ID/backend', '--platform', 'managed']

  # Deploy frontend service
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'frontend-service', '--image', 'gcr.io/$PROJECT_ID/frontend', '--platform', 'managed']
